Add configurable line width for `YamlBukkitConfigurer`
Required updating Spigot runtime from 1.12.2 -> 1.18.1, but NoSuchMethodError is caught when setting line width, so should be okay!